org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.installations.paths=C:/Users/nostraxiten/Downloads/Root/Codigo/26.2/RootCode/jdk25/jdk-25.0.4+7,C:/Users/nostraxiten/Downloads/Root/Codigo/1.21.11/RootCode/jdk21/jdk-21.0.2+13

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.0.0
maven_group=com.nox.menu
archives_base_name=RootV1-26.2

fabric_version=0.153.0+26.2
